Repository cdk-cosmos/cosmos, pull requests merged in 2020-10, with the labels that each got.

#209 ECS ROLLING_UPDATE
  packages/@cdk-cosmos/core/src/features/ecs-feature/ecs-feature-core-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
Labels: cdk-cosmos, enhancement

#212 Release 0.7.0
  changelog.md
  lerna.json
  package.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/README.md
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/features/ecs-feature/ecs-feature-core-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/README.md
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/common/src/cdk-tool-kit-app.ts
  packages/@cosmos-building-blocks/common/src/cdk-tool-kit.ts
  packages/@cosmos-building-blocks/common/src/cdk-toolkit/bootstrap-app.ts
  packages/@cosmos-building-blocks/common/src/cdk-toolkit/cdk-bootstrap.ts
  packages/@cosmos-building-blocks/common/src/cdk-toolkit/template.yaml
  packages/@cosmos-building-blocks/common/src/index.ts
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/service/package.json
  src/scripts/version.sh
  yarn.lock
Labels: release:minor

#213 Fix @aws-cdk/aws-kms peer dependency
  packages/@cdk-cosmos/core/package.json
Labels: bug
