Repository cdk-cosmos/cosmos, pull requests merged in 2020-07, with the labels that each got.

#101 Refactor pipelines + StandardPipeline + BuildSpecBuilder
  packages/@cdk-cosmos/core/src/ci-cd-ecs-solar-system.ts
  packages/@cdk-cosmos/core/src/ci-cd-solar-system.ts
  packages/@cdk-cosmos/core/src/components/cdk-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/app-node-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/build-spec.ts
  packages/@cosmos-building-blocks/pipeline/src/commands.ts
  packages/@cosmos-building-blocks/pipeline/src/docker-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/index.ts
  packages/@cosmos-building-blocks/pipeline/src/node-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/@cosmos-building-blocks/pipeline/test/lib-template.test.ts
  packages/@cosmos-building-blocks/pipeline/test/pipeline.test.ts
  shields/coverage.svg
Labels: building-block, cdk-cosmos, enhancement

#100 0.5.x Refactor Code
  packages/@cdk-cosmos/core/src/ci-cd-ecs-solar-system.ts
  packages/@cdk-cosmos/core/src/ci-cd-solar-system.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/index.ts
  packages/@cdk-cosmos/core/src/components/base.ts
  packages/@cdk-cosmos/core/src/cosmos.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmoc-core-link-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-import.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-extension-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/index.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/index.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-import.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-extension-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/index.ts
  packages/@cdk-cosmos/core/src/helpers/utils.ts
  packages/@cdk-cosmos/core/src/index.ts
  packages/@cdk-cosmos/core/src/solar-system/index.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ci-cd-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/ecs-solar-system.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cdk-cosmos/core/tsconfig.json
Labels: cdk-cosmos, enhancement

#139 Release v0.5.0
  changelog.md
  lerna.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/ci-cd-ecs-solar-system.ts
  packages/@cdk-cosmos/core/src/ci-cd-solar-system.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/index.ts
  packages/@cdk-cosmos/core/src/components/base.ts
  packages/@cdk-cosmos/core/src/components/cdk-pipeline.ts
  packages/@cdk-cosmos/core/src/cosmos.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmoc-core-link-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-import.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-extension-stack.ts
  packages/@cdk-cosmos/core/src/cosmos/index.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/index.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-import.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-extension-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/index.ts
  packages/@cdk-cosmos/core/src/helpers/utils.ts
  packages/@cdk-cosmos/core/src/index.ts
  packages/@cdk-cosmos/core/src/solar-system/index.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ci-cd-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/ecs-solar-system.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cdk-cosmos/core/tsconfig.json
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/common/src/cdk-tool-kit.ts
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/pipeline/src/app-node-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/build-spec.ts
  packages/@cosmos-building-blocks/pipeline/src/commands.ts
  packages/@cosmos-building-blocks/pipeline/src/docker-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/index.ts
  packages/@cosmos-building-blocks/pipeline/src/node-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/@cosmos-building-blocks/pipeline/test/lib-template.test.ts
  packages/@cosmos-building-blocks/pipeline/test/pipeline.test.ts
  packages/@cosmos-building-blocks/service/package.json
  packages/@cosmos-building-blocks/service/src/index.ts
  packages/@cosmos-building-blocks/service/src/s3.ts
  packages/@cosmos-building-blocks/service/test/__snapshots__/s3.test.ts.snap
  packages/@cosmos-building-blocks/service/test/s3.test.ts
  packages/private/cross-account-stack-ref-handler/package.json
  shields/coverage.svg
Labels: release:minor

#140 Fix typescript typing issue from refactor in v0.5.0
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/tsconfig.json
Labels: bug

#141 Release v0.5.1
  changelog.md
  lerna.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/cicd-solar-system/cicd-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/tsconfig.json
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/service/package.json
  packages/private/cross-account-stack-ref-handler/package.json
Labels: release:patch

#142 A Couple of Small Fixes ( Pipeline repo cross stack + Alb dns export issue)
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/helpers/remote.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ci-cd-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cosmos-building-blocks/pipeline/src/commands.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
Labels: bug

#143 Fix portal scope issue
  packages/@cdk-cosmos/core/src/components/base.ts
  packages/@cdk-cosmos/core/src/components/cdk-pipeline.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-import.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-import.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-extension-stack.ts
  packages/@cdk-cosmos/core/src/helpers/generate-id.ts
  packages/@cdk-cosmos/core/src/helpers/generate-scope-id.ts
  packages/@cdk-cosmos/core/src/helpers/remote.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/cosmos.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/cosmos.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cosmos-building-blocks/service/test/s3.test.ts
Labels: bug, cdk-cosmos

#145 Release v0.5.2
  changelog.md
  lerna.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/components/base.ts
  packages/@cdk-cosmos/core/src/components/cdk-pipeline.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-core-import.ts
  packages/@cdk-cosmos/core/src/cosmos/cosmos-extension-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-core-import.ts
  packages/@cdk-cosmos/core/src/galaxy/galaxy-extension-stack.ts
  packages/@cdk-cosmos/core/src/helpers/generate-id.ts
  packages/@cdk-cosmos/core/src/helpers/generate-scope-id.ts
  packages/@cdk-cosmos/core/src/helpers/remote.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-core-import.ts
  packages/@cdk-cosmos/core/src/solar-system/solar-system-extension-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ci-cd-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/cosmos.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/cosmos.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/pipeline/src/commands.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/@cosmos-building-blocks/service/package.json
  packages/@cosmos-building-blocks/service/test/s3.test.ts
  packages/private/cross-account-stack-ref-handler/package.json
Labels: release:patch

#146 Bug Fixes: Typeo in Remote Imports, Default Privileged mode for Docker Pipeline, Bundle Issue in Cross Account Stack Ref Fn
  packages/@cdk-cosmos/core/src/helpers/remote.ts
  packages/@cdk-cosmos/core/test/cosmos.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cosmos-building-blocks/pipeline/src/docker-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/private/cross-account-stack-ref-handler/package.json
  packages/private/cross-account-stack-ref-handler/src/index.ts
  packages/private/cross-account-stack-ref-handler/src/send.ts
  packages/private/cross-account-stack-ref-handler/test/handler.test.ts
  yarn.lock
Labels: bug, building-block, cdk-cosmos

#147 Release v0.5.3
  changelog.md
  lerna.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/helpers/remote.ts
  packages/@cdk-cosmos/core/test/cosmos.test.ts
  packages/@cdk-cosmos/core/test/solar-system.test.ts
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/pipeline/src/docker-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/src/standard-pipeline.ts
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/@cosmos-building-blocks/service/package.json
  packages/private/cross-account-stack-ref-handler/package.json
  packages/private/cross-account-stack-ref-handler/src/index.ts
  packages/private/cross-account-stack-ref-handler/src/send.ts
  packages/private/cross-account-stack-ref-handler/test/handler.test.ts
  yarn.lock
Labels: release:patch

#148 Fix missing node modules in cross account fn (bundle issue)
  packages/private/cross-account-stack-ref-handler/package.json
Labels: bug, building-block

#151 Release v0.5.4
  cdk-test/app/package-lock.json
  cdk-test/core/package-lock.json
  changelog.md
  lerna.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/service/package.json
  packages/private/cross-account-stack-ref-handler/package.json
Labels: release:patch

#155 Added Redis Building block
  package.json
  packages/@cosmos-building-blocks/service/package.json
  packages/@cosmos-building-blocks/service/src/index.ts
  packages/@cosmos-building-blocks/service/src/redis.ts
  packages/@cosmos-building-blocks/service/test/__snapshots__/redis.test.ts.snap
  packages/@cosmos-building-blocks/service/test/redis.test.ts
  yarn.lock
Labels: building-block, enhancement

#156 Update AWS CDK + Default ASG for ECS
  cdk-test/app/.gitignore
  cdk-test/app/package-lock.json
  cdk-test/app/package.json
  cdk-test/core/.gitignore
  cdk-test/core/package-lock.json
  cdk-test/core/package.json
  package.json
  packages/@cdk-cosmos/cdk-credentials-plugin/package.json
  packages/@cdk-cosmos/core/package.json
  packages/@cdk-cosmos/core/src/ecs-solar-system/ecs-solar-system-core-stack.ts
  packages/@cdk-cosmos/core/test/__snapshots__/ci-cd-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/ecs-solar-system.test.ts.snap
  packages/@cdk-cosmos/core/test/__snapshots__/solar-system.test.ts.snap
  packages/@cosmos-building-blocks/app-ec2/package.json
  packages/@cosmos-building-blocks/common/package.json
  packages/@cosmos-building-blocks/network/package.json
  packages/@cosmos-building-blocks/network/test/__snapshots__/tgw-connect.test.ts.snap
  packages/@cosmos-building-blocks/network/test/__snapshots__/transparent-proxy.test.ts.snap
  packages/@cosmos-building-blocks/pipeline/package.json
  packages/@cosmos-building-blocks/pipeline/test/__snapshots__/pipeline.test.ts.snap
  packages/@cosmos-building-blocks/service/package.json
  packages/@cosmos-building-blocks/service/test/__snapshots__/redis.test.ts.snap
  src/test/mocks.ts
  template/package.json
  yarn.lock
Labels: building-block, cdk-cosmos, dependencies, enhancement
